# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hackndo
email: hackndo@gmail.com
description: Ce blog est dédié à la sécurité informatique. Tutos sur le fonctionnement de la pile, les buffers overflow, on explique tout avec des exemples concrets.
tagline: Think out of the box
baseurl: "/" # the subpath of your site, e.g. /blog
root: /
url: "http://beta.hackndo.com" # the base hostname & protocol for your site
author: Pixis
twitter_username: hackanddo
github_username:  hackndo
logo: "/assets/icones/logo.png"
social:
    name: Pixis
    links:
        - https://github.com/hackndo
        - https://twitter.com/hackanddo
        - https://www.newbiecontest.org/index.php?page=info_membre&nick=pixis
        - https://www.root-me.org/Betezed
        - https://unikard.xyz/pbq8b
lang: fr_FR

# Build settings
markdown: kramdown

paginate: 8
paginate_path: "page/:num"
github:
  repo:
    "http://github.com/hackndo/hackndo.github.io"
version: 1.1.0
gems:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

excerpt_separator: <!--more-->
